<?php
echo $form_id;
echo $form_open;
echo $label_name;
echo $form_name;
echo("</br>");
echo $label_alterego;
echo $form_alterego;
echo("</br>");
echo $label_aliases;
echo $form_aliases;
echo("</br>");
echo $label_placeofbirth;
echo $form_placeofbirth;
echo("</br>");
echo $label_firstappearance;
echo $form_firstappearance;
echo("</br>");
echo $label_alignment;
echo $form_alignment;
echo("</br>");
echo $form_submit;
echo $form_close;
